FROM ubuntu:18.04 AS builder
WORKDIR /project
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get -qq update && \
    apt-get -qq install -y cmake git vim gcc g++ gfortran software-properties-common likwid \
            mpich libmpich-dev \
            openmpi-bin openmpi-doc libopenmpi-dev

# Installing latest GCC compiler (version 10)
RUN add-apt-repository ppa:ubuntu-toolchain-r/test
RUN apt-get -qq update && \
    apt-get -qq install -y gcc-10 g++-10 gfortran-10

# We can use the update alternatives to switch between compiler versions
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 80 \
                        --slave /usr/bin/g++ g++ /usr/bin/g++-7 \
                        --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-7 \
                        --slave /usr/bin/gcov gcov /usr/bin/gcov-7

RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 90 \
                        --slave /usr/bin/g++ g++ /usr/bin/g++-10 \
                        --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-10 \
                        --slave /usr/bin/gcov gcov /usr/bin/gcov-10

RUN chmod u+s /usr/bin/update-alternatives

RUN apt-get clean && rm -rf /var/lib/apt/lists/*
ENV unset DEBIAN_FRONTEND

SHELL ["/bin/bash", "-c"]

RUN groupadd chapter14 && useradd -m -s /bin/bash -g chapter14 chapter14

WORKDIR /home/chapter14
RUN chown -R chapter14:chapter14 /home/chapter14
USER chapter14

RUN git clone --recursive https://github.com/essentialsofparallelcomputing/Chapter14.git

WORKDIR /home/chapter14/Chapter14
#RUN make

ENTRYPOINT ["bash"]
